name: dev build
on:
  push:
    branches:
      - '**'        # matches every branch
jobs:
  build:
    name: dev build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install and Build 
        run: |
          cd frontend
          npm ci
          npm run build

